In [14]:
import numpy as np
import pandas as pd
from pymongo import MongoClient

Mongo Connections

In [15]:
client = MongoClient('localhost', 27017)
db = client['spotify_analysis']

Get dataset from database and convert to Pandas Dataframe

In [16]:
dataset = db.dataset.find({})
dataframe =  pd.DataFrame(list(dataset))

Print dataframe

In [17]:
dataframe

,_id,music_name,artist,first_week,second_week,third_week,fourth_week,january,february,march,...,acousticness,danceability,energy,instrumentalness,liveness,loudness,speechiness,valence,tempo,position
0,5dd48bb2331099cd95f947ff,Deu Onda,MC G15,1,0,0,0,1,0,0,...,0.4560,0.931,0.604,0.000000,0.0488,-1.410,0.0573,0.864,129.926,10.0
1,5dd48bb2331099cd95f94800,Hear Me Now,Alok,1,0,0,0,1,0,0,...,0.5860,0.789,0.442,0.003660,0.0927,-7.844,0.0421,0.450,121.971,10.0
2,5dd48bb2331099cd95f94801,10% - Ao Vivo,Maiara & Maraisa,1,0,0,0,1,0,0,...,0.4820,0.632,0.950,0.000000,0.8400,-2.850,0.1110,0.596,154.006,10.0
3,5dd48bb2331099cd95f94802,Eu Sei de Cor - Ao Vivo | Acústico,Marília Mendonça,1,0,0,0,1,0,0,...,0.4240,0.855,0.601,0.000000,0.2410,-5.902,0.0346,0.776,124.016,10.0
4,5dd48bb2331099cd95f94803,Meu Coração Deu PT - Ao Vivo,Wesley Safadão,1,0,0,0,1,0,0,...,0.0916,0.647,0.930,0.000000,0.4010,-3.147,0.0636,0.848,133.966,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199795,5dd48bb8331099cd95fc5472,SAD!,XXXTENTACION,0,0,0,1,0,0,0,...,0.2580,0.740,0.613,0.003720,0.1230,-4.880,0.1450,0.473,75.023,200.0
199796,5dd48bb8331099cd95fc5473,Sweater Weather,The Neighbourhood,0,0,0,1,0,0,0,...,0.0495,0.612,0.807,0.017700,0.1010,-2.810,0.0336,0.398,124.053,200.0
199797,5dd48bb8331099cd95fc5474,Era uma Vez,Kell Smith,0,0,0,1,0,0,0,...,0.4850,0.680,0.449,0.000000,0.1290,-6.983,0.0324,0.145,94.842,200.0
199798,5dd48bb8331099cd95fc5475,Paga De Solteiro Feliz,Simone & Simaria,0,0,0,1,0,0,0,...,0.0383,0.686,0.945,0.000014,0.0898,-3.123,0.0598,0.112,98.008,200.0
199799,5dd48bb8331099cd95fc5476,These Days,Rudimental,0,0,0,1,0,0,0,...,0.1940,0.653,0.809,0.000000,0.1650,-4.057,0.0474,0.550,92.213,200.0

Delete unuseful columns

In [18]:
modified_df = dataframe
del modified_df["_id"]
del modified_df["music_name"]
del modified_df["artist"]

modified_df

,first_week,second_week,third_week,fourth_week,january,february,march,april,may,june,...,acousticness,danceability,energy,instrumentalness,liveness,loudness,speechiness,valence,tempo,position
0,1,0,0,0,1,0,0,0,0,0,...,0.4560,0.931,0.604,0.000000,0.0488,-1.410,0.0573,0.864,129.926,10.0
1,1,0,0,0,1,0,0,0,0,0,...,0.5860,0.789,0.442,0.003660,0.0927,-7.844,0.0421,0.450,121.971,10.0
2,1,0,0,0,1,0,0,0,0,0,...,0.4820,0.632,0.950,0.000000,0.8400,-2.850,0.1110,0.596,154.006,10.0
3,1,0,0,0,1,0,0,0,0,0,...,0.4240,0.855,0.601,0.000000,0.2410,-5.902,0.0346,0.776,124.016,10.0
4,1,0,0,0,1,0,0,0,0,0,...,0.0916,0.647,0.930,0.000000,0.4010,-3.147,0.0636,0.848,133.966,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199795,0,0,0,1,0,0,0,1,0,0,...,0.2580,0.740,0.613,0.003720,0.1230,-4.880,0.1450,0.473,75.023,200.0
199796,0,0,0,1,0,0,0,1,0,0,...,0.0495,0.612,0.807,0.017700,0.1010,-2.810,0.0336,0.398,124.053,200.0
199797,0,0,0,1,0,0,0,1,0,0,...,0.4850,0.680,0.449,0.000000,0.1290,-6.983,0.0324,0.145,94.842,200.0
199798,0,0,0,1,0,0,0,1,0,0,...,0.0383,0.686,0.945,0.000014,0.0898,-3.123,0.0598,0.112,98.008,200.0
199799,0,0,0,1,0,0,0,1,0,0,...,0.1940,0.653,0.809,0.000000,0.1650,-4.057,0.0474,0.550,92.213,200.0

Divide train and test dataset

In [30]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(modified_df, test_size=0.2)

In [31]:
train_y = train[['position']]
test_y = test[['position']]

del train['position']
del test['position']

In [33]:
test

,first_week,second_week,third_week,fourth_week,january,february,march,april,may,june,...,december,acousticness,danceability,energy,instrumentalness,liveness,loudness,speechiness,valence,tempo
77431,0,0,0,1,1,0,0,0,0,0,...,0,0.1960,0.648,0.833,0.000000,0.3130,-6.323,0.2580,0.691,135.666
157081,1,0,0,0,0,0,1,0,0,0,...,0,0.0202,0.823,0.474,0.000000,0.2010,-9.290,0.0503,0.833,95.050
93983,0,0,1,0,0,0,0,1,0,0,...,0,0.0711,0.599,0.512,0.000000,0.0816,-2.578,0.0641,0.725,87.838
13627,0,1,0,0,0,0,1,0,0,0,...,0,0.9010,0.604,0.433,0.000000,0.6760,-6.256,0.0339,0.257,139.696
140981,0,1,0,0,0,0,0,0,0,0,...,1,0.0410,0.729,0.849,0.000014,0.0665,-3.925,0.0325,0.558,123.990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130851,0,0,0,1,0,0,0,0,0,0,...,0,0.1760,0.694,0.770,0.000011,0.1180,-5.335,0.1490,0.163,125.905
142855,0,0,1,0,0,0,0,0,0,0,...,1,0.8010,0.538,0.651,0.000000,0.9480,-5.805,0.0336,0.544,148.030
141138,0,1,0,0,0,0,0,0,0,0,...,1,0.2780,0.670,0.830,0.000000,0.2100,-8.691,0.0598,0.871,155.047
80293,0,1,0,0,0,1,0,0,0,0,...,0,0.2530,0.504,0.837,0.000000,0.1550,-2.917,0.2760,0.801,179.877
181726,1,0,0,0,0,0,0,0,0,0,...,0,0.6110,0.694,0.869,0.000000,0.5350,-5.260,0.0857,0.786,121.996

In [35]:
test_y

        position
77431       50.0
157081     100.0
93983      200.0
13627       50.0
140981     200.0
...          ...
130851     100.0
142855     100.0
141138     200.0
80293      100.0
181726     200.0

[39960 rows x 1 columns]

In [46]:
train

,first_week,second_week,third_week,fourth_week,january,february,march,april,may,june,...,december,acousticness,danceability,energy,instrumentalness,liveness,loudness,speechiness,valence,tempo
171164,0,1,0,0,0,0,0,0,1,0,...,0,0.08280,0.844,0.644,0.000000,0.1130,-6.273,0.0479,0.591,122.061
94437,0,0,0,1,0,0,0,1,0,0,...,0,0.11300,0.647,0.713,0.007030,0.1460,-5.874,0.0256,0.277,124.982
90182,1,0,0,0,0,0,0,1,0,0,...,0,0.04950,0.612,0.807,0.017700,0.1010,-2.810,0.0336,0.398,124.053
127583,1,0,0,0,0,0,0,0,0,0,...,0,0.22500,0.884,0.570,0.000000,0.2000,-2.451,0.0503,0.817,129.967
74993,0,0,1,0,1,0,0,0,0,0,...,0,0.11800,0.697,0.716,0.000000,0.0424,-6.288,0.1130,0.506,99.905
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10830,0,0,1,0,0,1,0,0,0,0,...,0,0.42700,0.655,0.913,0.000000,0.1050,-3.585,0.1330,0.918,171.961
20221,0,1,0,0,0,0,0,1,0,0,...,0,0.02150,0.653,0.658,0.000002,0.0939,-6.428,0.0304,0.219,99.990
119220,0,0,0,1,0,0,0,0,0,0,...,0,0.01480,0.871,0.832,0.000000,0.1210,-5.261,0.0373,0.569,135.062
53781,1,0,0,0,0,0,0,0,0,0,...,0,0.06720,0.929,0.723,0.000000,0.3460,-5.792,0.1090,0.458,125.022
86163,0,1,0,0,0,0,1,0,0,0,...,0,0.00104,0.922,0.581,0.000059,0.1050,-7.495,0.2700,0.595,140.022

In [47]:
train_y

        position
171164     200.0
94437       50.0
90182      200.0
127583     200.0
74993      200.0
...          ...
10830       50.0
20221       50.0
119220      50.0
53781      200.0
86163      200.0

[159840 rows x 1 columns]

Creating a Neural Network

In [48]:
'''import tensorflow as tf
from tensorflow import keras

len_train = len(train)

model = keras.Sequential([
    keras.layers.Flatten(input_shape=(len_train, 25)),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(10, activation='softmax')
])


model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(train, train_y, epochs=10)'''

"import tensorflow as tf\nfrom tensorflow import keras\n\nlen_train = len(train)\n\nmodel = keras.Sequential([\n    keras.layers.Flatten(input_shape=(len_train, 25)),\n    keras.layers.Dense(128, activation='relu'),\n    keras.layers.Dense(10, activation='softmax')\n])\n\n\nmodel.compile(optimizer='adam',\n              loss='sparse_categorical_crossentropy',\n              metrics=['accuracy'])\n\nmodel.fit(train, train_y, epochs=10)"

In [82]:
from sklearn.neural_network import MLPClassifier


mlp_classifier = MLPClassifier(solver = "adam", hidden_layer_sizes=(64,64,64,64), verbose=True, max_iter=200, alpha=0.0001, tol=1e-4)

mlp_classifier.fit(train,train_y.values.ravel())

Iteration 1, loss = 1.22258070
Iteration 2, loss = 1.16799767
Iteration 3, loss = 1.15926047
Iteration 4, loss = 1.15876464
Iteration 5, loss = 1.15646318
Iteration 6, loss = 1.15353710
Iteration 7, loss = 1.15304146
Iteration 8, loss = 1.15146541
Iteration 9, loss = 1.14960961
Iteration 10, loss = 1.14763972
Iteration 11, loss = 1.14583448
Iteration 12, loss = 1.14418884
Iteration 13, loss = 1.14207445
Iteration 14, loss = 1.13825610
Iteration 15, loss = 1.13239030
Iteration 16, loss = 1.12677830
Iteration 17, loss = 1.12019274
Iteration 18, loss = 1.11223982
Iteration 19, loss = 1.10723975
Iteration 20, loss = 1.10117264
Iteration 21, loss = 1.09499829
Iteration 22, loss = 1.09088253
Iteration 23, loss = 1.08124059
Iteration 24, loss = 1.07477152
Iteration 25, loss = 1.07028915
Iteration 26, loss = 1.06271728
Iteration 27, loss = 1.05790666
Iteration 28, loss = 1.05635636
Iteration 29, loss = 1.04887780
Iteration 30, loss = 1.04429949
Iteration 31, loss = 1.03965130
Iteration 32, loss = 1.03593323
Iteration 33, loss = 1.03443401
Iteration 34, loss = 1.02700648
Iteration 35, loss = 1.02405053
Iteration 36, loss = 1.01913513
Iteration 37, loss = 1.01757154
Iteration 38, loss = 1.01322886
Iteration 39, loss = 1.00865348
Iteration 40, loss = 1.00701537
Iteration 41, loss = 1.00316953
Iteration 42, loss = 0.99863152
Iteration 43, loss = 0.99800093
Iteration 44, loss = 0.99408792
Iteration 45, loss = 0.99025308
Iteration 46, loss = 0.98868985
Iteration 47, loss = 0.98458167
Iteration 48, loss = 0.98237070
Iteration 49, loss = 0.98099044
Iteration 50, loss = 0.97661396
Iteration 51, loss = 0.97614636
Iteration 52, loss = 0.97510912
Iteration 53, loss = 0.97218550
Iteration 54, loss = 0.97207462
Iteration 55, loss = 0.96721513
Iteration 56, loss = 0.96694124
Iteration 57, loss = 0.96289625
Iteration 58, loss = 0.96357340
Iteration 59, loss = 0.96023157
Iteration 60, loss = 0.96072548
Iteration 61, loss = 0.95877531
Iteration 62, loss = 0.95921811
Iteration 63, loss = 0.95228150
Iteration 64, loss = 0.95248881
Iteration 65, loss = 0.95238792
Iteration 66, loss = 0.95208561
Iteration 67, loss = 0.94690115
Iteration 68, loss = 0.94446875
Iteration 69, loss = 0.94459405
Iteration 70, loss = 0.94176452
Iteration 71, loss = 0.94193393
Iteration 72, loss = 0.93960972
Iteration 73, loss = 0.93943062
Iteration 74, loss = 0.93692445
Iteration 75, loss = 0.93741072
Iteration 76, loss = 0.93527746
Iteration 77, loss = 0.93493190
Iteration 78, loss = 0.92957980
Iteration 79, loss = 0.93302836
Iteration 80, loss = 0.93019094
Iteration 81, loss = 0.92831634
Iteration 82, loss = 0.92953013
Iteration 83, loss = 0.92646286
Iteration 84, loss = 0.92368788
Iteration 85, loss = 0.92571386
Iteration 86, loss = 0.92400241
Iteration 87, loss = 0.92047914
Iteration 88, loss = 0.92113655
Iteration 89, loss = 0.92161344
Iteration 90, loss = 0.92076519
Iteration 91, loss = 0.92065586
Iteration 92, loss = 0.91806625
Iteration 93, loss = 0.92258851
Iteration 94, loss = 0.91596848
Iteration 95, loss = 0.91369150
Iteration 96, loss = 0.91479627
Iteration 97, loss = 0.91508914
Iteration 98, loss = 0.91449589
Iteration 99, loss = 0.91497986
Iteration 100, loss = 0.91117796
Iteration 101, loss = 0.91274241
Iteration 102, loss = 0.91006038
Iteration 103, loss = 0.91107894
Iteration 104, loss = 0.90912679
Iteration 105, loss = 0.90970575
Iteration 106, loss = 0.90876367
Iteration 107, loss = 0.90642529
Iteration 108, loss = 0.90939121
Iteration 109, loss = 0.90973765
Iteration 110, loss = 0.90372083
Iteration 111, loss = 0.90463119
Iteration 112, loss = 0.90664881
Iteration 113, loss = 0.90746907
Iteration 114, loss = 0.90323009
Iteration 115, loss = 0.90064309
Iteration 116, loss = 0.90212623
Iteration 117, loss = 0.90086512
Iteration 118, loss = 0.90104757
Iteration 119, loss = 0.90120215
Iteration 120, loss = 0.89975219
Iteration 121, loss = 0.90105660
Iteration 122, loss = 0.89712388
Iteration 123, loss = 0.89849022
Iteration 124, loss = 0.89849338
Iteration 125, loss = 0.89751588
Iteration 126, loss = 0.89746683
Iteration 127, loss = 0.89612947
Iteration 128, loss = 0.89219008
Iteration 129, loss = 0.89262924
Iteration 130, loss = 0.89664322
Iteration 131, loss = 0.89129171
Iteration 132, loss = 0.89569116
Iteration 133, loss = 0.89012051
Iteration 134, loss = 0.89454583
Iteration 135, loss = 0.89115947
Iteration 136, loss = 0.89093085
Iteration 137, loss = 0.89134728
Iteration 138, loss = 0.89177563
Iteration 139, loss = 0.89003132
Iteration 140, loss = 0.88727580
Iteration 141, loss = 0.88764725
Iteration 142, loss = 0.88820382
Iteration 143, loss = 0.88862149
Iteration 144, loss = 0.88746863
Iteration 145, loss = 0.88942694
Iteration 146, loss = 0.88469577
Iteration 147, loss = 0.88801443
Iteration 148, loss = 0.88783083
Iteration 149, loss = 0.88611833
Iteration 150, loss = 0.88428910
Iteration 151, loss = 0.88293061
Iteration 152, loss = 0.88309095
Iteration 153, loss = 0.88629405
Iteration 154, loss = 0.88330038
Iteration 155, loss = 0.87911548
Iteration 156, loss = 0.88269497
Iteration 157, loss = 0.88250189
Iteration 158, loss = 0.88147548
Iteration 159, loss = 0.88260641
Iteration 160, loss = 0.88060506
Iteration 161, loss = 0.87966831
Iteration 162, loss = 0.88030141
Iteration 163, loss = 0.88210822
Iteration 164, loss = 0.87697815
Iteration 165, loss = 0.88292230
Iteration 166, loss = 0.87890554
Iteration 167, loss = 0.87970089
Iteration 168, loss = 0.87975516
Iteration 169, loss = 0.87820888
Iteration 170, loss = 0.87648686
Iteration 171, loss = 0.87654202
Iteration 172, loss = 0.87814309
Iteration 173, loss = 0.87564690
Iteration 174, loss = 0.87887591
Iteration 175, loss = 0.87391841
Iteration 176, loss = 0.87344871
Iteration 177, loss = 0.87514424
Iteration 178, loss = 0.87820008
Iteration 179, loss = 0.87454075
Iteration 180, loss = 0.87369682
Iteration 181, loss = 0.87347826
Iteration 182, loss = 0.87530413
Iteration 183, loss = 0.87103866
Iteration 184, loss = 0.87074209
Iteration 185, loss = 0.86922095
Iteration 186, loss = 0.87422296
Iteration 187, loss = 0.87353893
Iteration 188, loss = 0.87201033
Iteration 189, loss = 0.86918988
Iteration 190, loss = 0.87023372
Iteration 191, loss = 0.87029423
Iteration 192, loss = 0.87185419
Iteration 193, loss = 0.87213719
Iteration 194, loss = 0.86535808
Iteration 195, loss = 0.86970522
Iteration 196, loss = 0.86918336
Iteration 197, loss = 0.87109135
Iteration 198, loss = 0.86642204
Iteration 199, loss = 0.86502806
Iteration 200, loss = 0.86865471

/home/eduardo/.local/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(64, 64, 64, 64), learning_rate='constant',
              learning_rate_init=0.001, max_iter=200, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=True, warm_start=False)

In [83]:
training_set_score = mlp_classifier.score(train,train_y.values.ravel())
training_set_score

0.6095970970970971

In [84]:
training_set_score = mlp_classifier.score(test,test_y.values.ravel())
training_set_score

0.600975975975976

In [85]:
test.iloc[1].values

array([ 1.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,
        0.000e+00,  1.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,
        0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,
        0.000e+00,  2.020e-02,  8.230e-01,  4.740e-01,  0.000e+00,
        2.010e-01, -9.290e+00,  5.030e-02,  8.330e-01,  9.505e+01])

In [99]:
test_y.iloc[32]

position    10.0
Name: 35402, dtype: float64

In [100]:
mlp_classifier.predict([test.iloc[32]])

array([50.])

In [101]:
mlp_classifier.predict_proba([test.iloc[32]])

array([[0.26738516, 0.36267085, 0.15167181, 0.21827219]])